# Generated by Django 3.0.8 on 2021-04-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('account', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('account_name', models.CharField(blank=True, default='', max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
                'ordering': ['category'],
            },
        ),
    ]
