# Generated by Django 3.0.8 on 2021-04-07 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('introml', '0002_companies_companyperiodaccountgeneral_companyperiodaccountvalue_periods'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyperiodaccountgeneral',
            options={'verbose_name': 'general', 'verbose_name_plural': 'generals'},
        ),
        migrations.AlterModelOptions(
            name='periods',
            options={'verbose_name': 'period', 'verbose_name_plural': 'periods'},
        ),
    ]
