# Generated by Django 3.0.8 on 2021-04-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introml', '0004_auto_20210407_0822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyperiodaccountgeneral',
            options={'verbose_name': 'CompanyPeriodAccountGeneral', 'verbose_name_plural': 'CompanyPeriodAccountGenerals'},
        ),
        migrations.AlterModelOptions(
            name='companyperiodaccountvalue',
            options={'verbose_name': 'CompanyPeriodAccountValue', 'verbose_name_plural': 'CompanyPeriodAccountValues'},
        ),
        migrations.AlterField(
            model_name='companyperiodaccountgeneral',
            name='value',
            field=models.CharField(blank=True, default='', max_length=1020, null=True),
        ),
    ]
