# Generated by Django 3.0.8 on 2021-04-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introml', '0005_auto_20210408_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyperiodaccountvalue',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=21),
        ),
    ]
