# Generated by Django 3.0.8 on 2020-07-27 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(blank=True, max_length=10)),
                ('security_name', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'verbose_name': 'fund',
                'verbose_name_plural': 'funds',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_date', models.DateTimeField(null=True)),
                ('open', models.DecimalField(decimal_places=6, max_digits=12)),
                ('high', models.DecimalField(decimal_places=6, max_digits=12)),
                ('low', models.DecimalField(decimal_places=6, max_digits=12)),
                ('close', models.DecimalField(decimal_places=6, max_digits=12)),
                ('adj_close', models.DecimalField(decimal_places=6, max_digits=12)),
                ('volume', models.IntegerField()),
                ('yy_mm_dd', models.IntegerField(default=0)),
                ('security', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='core.Security')),
            ],
            options={
                'verbose_name': 'price',
                'verbose_name_plural': 'prices',
            },
        ),
    ]
