# Generated by Django 3.0.8 on 2020-07-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='security',
            options={'ordering': ['id'], 'verbose_name': 'fund', 'verbose_name_plural': 'funds'},
        ),
        migrations.AlterField(
            model_name='price',
            name='price_date',
            field=models.DateField(null=True),
        ),
    ]
