# Generated by Django 3.0.8 on 2020-08-14 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200728_0148'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'security group',
                'verbose_name_plural': 'security group',
                'ordering': ['group'],
            },
        ),
        migrations.AddField(
            model_name='security',
            name='security_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='securities', to='core.SecurityGroup'),
        ),
    ]
