# Generated by Django 3.0.8 on 2021-01-30 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200815_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='security',
            options={'ordering': ['symbol'], 'verbose_name': 'security', 'verbose_name_plural': 'securities'},
        ),
    ]
